-- =====================================================
-- COMPLETE DATABASE SCHEMA FOR DERMIT
-- Extracted from backup and migrations
-- =====================================================

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;

-- Create enum types
CREATE TYPE public.user_role AS ENUM ('admin', 'doctor', 'patient');
CREATE TYPE public.status_enum AS ENUM ('active', 'inactive');
CREATE TYPE public.user_gender AS ENUM ('female', 'male');

-- =====================================================
-- TABLES
-- =====================================================

-- 1. Profiles table (depends on auth.users)
CREATE TABLE public.profiles (
    id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    email text NOT NULL,
    first_name text,
    last_name text,
    phone text,
    dob date,
    gender public.user_gender,
    consent_privacy boolean DEFAULT false,
    consent_terms boolean DEFAULT false,
    consent_timestamp timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    PRIMARY KEY (id)
);

-- 2. User roles table
CREATE TABLE public.user_roles (
    id uuid DEFAULT extensions.gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    role public.user_role NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (user_id, role)
);

-- 3. Doctors info table
CREATE TABLE public.doctors_info (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    profile_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    specialty text,
    license_number text,
    education text,
    bio text,
    certifications text,
    years_of_experience integer,
    profile_pic text,
    status public.status_enum DEFAULT 'active',
    created_at timestamp with time zone DEFAULT now(),
    PRIMARY KEY (id)
);

-- 4. Consultations table
CREATE TABLE public.consultations (
    id uuid DEFAULT extensions.gen_random_uuid() NOT NULL,
    patient_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    doctor_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    title text NOT NULL,
    description text,
    diagnosis text,
    observations text,
    treatment_plan text,
    images text[],
    status text DEFAULT 'pending',
    priority text DEFAULT 'normal',
    payment_id text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    PRIMARY KEY (id)
);

-- 5. Chats table
CREATE TABLE public.chats (
    id uuid DEFAULT extensions.gen_random_uuid() NOT NULL,
    consultation_id uuid NOT NULL REFERENCES public.consultations(id) ON DELETE CASCADE,
    doctor_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    patient_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    status character varying(20) DEFAULT 'active' NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    PRIMARY KEY (id)
);

-- 6. Messages table
CREATE TABLE public.messages (
    id uuid DEFAULT extensions.gen_random_uuid() NOT NULL,
    chat_id uuid REFERENCES public.chats(id) ON DELETE SET NULL,
    consultation_id uuid NOT NULL REFERENCES public.consultations(id) ON DELETE CASCADE,
    sender_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    content text NOT NULL,
    message_type text DEFAULT 'text',
    file_url text,
    created_at timestamp with time zone DEFAULT now(),
    PRIMARY KEY (id)
);

-- 7. Notifications table
CREATE TABLE public.notifications (
    id uuid DEFAULT extensions.gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    title text NOT NULL,
    message text NOT NULL,
    type text DEFAULT 'info',
    is_read boolean DEFAULT false,
    consultation_id uuid REFERENCES public.consultations(id) ON DELETE CASCADE,
    created_at timestamp with time zone DEFAULT now(),
    PRIMARY KEY (id)
);

-- 8. Media assets table
CREATE TABLE public.media_assets (
    id uuid DEFAULT extensions.gen_random_uuid() NOT NULL,
    consultation_id uuid REFERENCES public.consultations(id) ON DELETE SET NULL,
    image_url text,
    image_type text,
    created_at timestamp with time zone DEFAULT now(),
    PRIMARY KEY (id)
);

-- 9. Patient feedback table
CREATE TABLE public.patient_feedback (
    id uuid DEFAULT extensions.gen_random_uuid() NOT NULL,
    user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    consultation_id uuid REFERENCES public.consultations(id) ON DELETE SET NULL,
    rating integer,
    feedback_message text,
    allow_contact boolean DEFAULT false,
    contact_method text,
    contact_value text,
    created_at timestamp with time zone DEFAULT now(),
    PRIMARY KEY (id)
);

-- 10. Telegram subscribers table
CREATE TABLE public."telegramBotSubscribers" (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id uuid NOT NULL,
    chat_id text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    PRIMARY KEY (id)
);

-- 11. Doctor registrations table
CREATE TABLE public.doctor_registrations (
    id uuid DEFAULT extensions.gen_random_uuid() NOT NULL,
    full_name text NOT NULL,
    phone text NOT NULL,
    email text NOT NULL,
    city_country text NOT NULL,
    experience integer NOT NULL,
    medical_license_url text NOT NULL,
    status text DEFAULT 'pending',
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    reviewed_by uuid REFERENCES auth.users(id),
    reviewed_at timestamp with time zone,
    rejection_reason text,
    PRIMARY KEY (id)
);


-- =====================================================
-- FUNCTIONS
-- =====================================================

-- Function to check user role
CREATE OR REPLACE FUNCTION public.has_role(_user_id uuid, _role public.user_role)
RETURNS boolean
LANGUAGE sql
STABLE SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.user_roles
    WHERE user_id = _user_id AND role = _role
  );
$$;

-- Function to handle new user signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, email, first_name, last_name)
  VALUES (
    NEW.id, 
    NEW.email, 
    NEW.raw_user_meta_data ->> 'first_name', 
    NEW.raw_user_meta_data ->> 'last_name'
  );
  RETURN NEW;
END;
$$;

-- Trigger for new user
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Function to update consultation timestamp
CREATE OR REPLACE FUNCTION public.update_consultation_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

CREATE TRIGGER update_consultations_updated_at
  BEFORE UPDATE ON public.consultations
  FOR EACH ROW EXECUTE FUNCTION public.update_consultation_updated_at();

-- Function to notify doctors of new consultation
CREATE OR REPLACE FUNCTION public.notify_doctors_new_consultation()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.notifications (user_id, title, message, type, consultation_id)
  SELECT 
    p.id,
    'New Consultation Request',
    'A new consultation request has been submitted: ' || NEW.title,
    'info',
    NEW.id
  FROM public.profiles p
  JOIN public.user_roles ur ON p.id = ur.user_id
  WHERE ur.role = 'doctor';
  
  RETURN NEW;
END;
$$;

CREATE TRIGGER on_consultation_created
  AFTER INSERT ON public.consultations
  FOR EACH ROW EXECUTE FUNCTION public.notify_doctors_new_consultation();

-- Function to accept consultation
CREATE OR REPLACE FUNCTION public.accept_consultation(consult_id uuid, doc_id uuid)
RETURNS boolean
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
  rows_updated INT;
BEGIN
  UPDATE public.consultations
  SET doctor_id = doc_id, status = 'in_progress'
  WHERE id = consult_id AND status = 'pending';

  GET DIAGNOSTICS rows_updated = ROW_COUNT;
  RETURN rows_updated = 1;
END;
$$;

-- Function to update doctor
CREATE OR REPLACE FUNCTION public.update_doctor(
  p_doctor_id uuid, 
  p_first_name text, 
  p_last_name text, 
  p_email text, 
  p_phone text, 
  p_specialty text, 
  p_profilepic text
)
RETURNS void
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  UPDATE public.profiles
  SET first_name = p_first_name, last_name = p_last_name, email = p_email, phone = p_phone
  WHERE id = p_doctor_id;

  UPDATE public.doctors_info
  SET specialty = p_specialty, profile_pic = p_profilepic
  WHERE profile_id = p_doctor_id;
END;
$$;

-- Function for doctor registration notification
CREATE OR REPLACE FUNCTION public.notify_admins_new_doctor_registration()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.notifications (user_id, title, message, type)
  SELECT 
    ur.user_id,
    'New Doctor Registration',
    'A new doctor has registered: ' || NEW.full_name || ' (' || NEW.email || ')',
    'info'
  FROM public.user_roles ur
  WHERE ur.role = 'admin';
  
  RETURN NEW;
END;
$$;

CREATE TRIGGER trigger_notify_admins_new_doctor_registration
  AFTER INSERT ON public.doctor_registrations
  FOR EACH ROW EXECUTE FUNCTION public.notify_admins_new_doctor_registration();


-- =====================================================
-- ROW LEVEL SECURITY (RLS)
-- =====================================================

-- Enable RLS on all tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.doctors_info ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.consultations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.media_assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.patient_feedback ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."telegramBotSubscribers" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.doctor_registrations ENABLE ROW LEVEL SECURITY;

-- Profiles policies
CREATE POLICY "Users can view their own profile" ON public.profiles
  FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update their own profile" ON public.profiles
  FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Admins can view all profiles" ON public.profiles
  FOR SELECT USING (public.has_role(auth.uid(), 'admin'));
CREATE POLICY "Admins can update all profiles" ON public.profiles
  FOR UPDATE USING (public.has_role(auth.uid(), 'admin'));

-- User roles policies
CREATE POLICY "Users can view their own roles" ON public.user_roles
  FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own role" ON public.user_roles
  FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Admins can manage roles" ON public.user_roles
  FOR UPDATE USING (public.has_role(auth.uid(), 'admin'));
CREATE POLICY "Admins can delete roles" ON public.user_roles
  FOR DELETE USING (public.has_role(auth.uid(), 'admin'));

-- Consultations policies
CREATE POLICY "Users can view their own consultations" ON public.consultations
  FOR SELECT USING (auth.uid() = patient_id OR auth.uid() = doctor_id OR public.has_role(auth.uid(), 'admin'));
CREATE POLICY "Patients can create consultations" ON public.consultations
  FOR INSERT WITH CHECK (auth.uid() = patient_id);
CREATE POLICY "Doctors and admins can update consultations" ON public.consultations
  FOR UPDATE USING (auth.uid() = doctor_id OR public.has_role(auth.uid(), 'admin'));

-- Chats policies
CREATE POLICY "Users can view chats in their consultations" ON public.chats
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.consultations c 
      WHERE c.id = consultation_id 
      AND (auth.uid() = c.patient_id OR auth.uid() = c.doctor_id OR public.has_role(auth.uid(), 'admin'))
    )
  );
CREATE POLICY "Users can create chats" ON public.chats
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.consultations c 
      WHERE c.id = consultation_id 
      AND (auth.uid() = c.patient_id OR auth.uid() = c.doctor_id OR public.has_role(auth.uid(), 'admin'))
    )
  );

-- Messages policies
CREATE POLICY "Users can view messages in their consultations" ON public.messages
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.consultations c 
      WHERE c.id = consultation_id 
      AND (auth.uid() = c.patient_id OR auth.uid() = c.doctor_id OR public.has_role(auth.uid(), 'admin'))
    )
  );
CREATE POLICY "Users can send messages" ON public.messages
  FOR INSERT WITH CHECK (
    auth.uid() = sender_id AND
    EXISTS (
      SELECT 1 FROM public.consultations c 
      WHERE c.id = consultation_id 
      AND (auth.uid() = c.patient_id OR auth.uid() = c.doctor_id OR public.has_role(auth.uid(), 'admin'))
    )
  );

-- Notifications policies
CREATE POLICY "Users can view their own notifications" ON public.notifications
  FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can update their own notifications" ON public.notifications
  FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "System can create notifications" ON public.notifications
  FOR INSERT WITH CHECK (true);

-- Media assets policies
CREATE POLICY "Users can view media in their consultations" ON public.media_assets
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.consultations c 
      WHERE c.id = consultation_id 
      AND (auth.uid() = c.patient_id OR auth.uid() = c.doctor_id OR public.has_role(auth.uid(), 'admin'))
    )
  );
CREATE POLICY "Users can upload media" ON public.media_assets
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.consultations c 
      WHERE c.id = consultation_id 
      AND (auth.uid() = c.patient_id OR auth.uid() = c.doctor_id OR public.has_role(auth.uid(), 'admin'))
    )
  );

-- Patient feedback policies
CREATE POLICY "Users can view their own feedback" ON public.patient_feedback
  FOR SELECT USING (auth.uid() = user_id OR public.has_role(auth.uid(), 'admin'));
CREATE POLICY "Users can create their own feedback" ON public.patient_feedback
  FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Doctor registrations policies
CREATE POLICY "Admins can view all doctor registrations" ON public.doctor_registrations
  FOR SELECT USING (public.has_role(auth.uid(), 'admin'));
CREATE POLICY "Admins can update doctor registrations" ON public.doctor_registrations
  FOR UPDATE USING (public.has_role(auth.uid(), 'admin'));
CREATE POLICY "Anyone can submit doctor registration" ON public.doctor_registrations
  FOR INSERT WITH CHECK (true);

-- Doctors info policies
CREATE POLICY "Doctors can view doctor info" ON public.doctors_info
  FOR SELECT USING (public.has_role(auth.uid(), 'doctor') OR public.has_role(auth.uid(), 'admin'));
CREATE POLICY "Doctors can update their own info" ON public.doctors_info
  FOR UPDATE USING (auth.uid() = profile_id OR public.has_role(auth.uid(), 'admin'));

-- Telegram subscribers policies
CREATE POLICY "Users can manage their own subscriptions" ON public."telegramBotSubscribers"
  FOR ALL USING (auth.uid() = user_id OR public.has_role(auth.uid(), 'admin'));


-- =====================================================
-- REALTIME
-- =====================================================

-- Enable replica identity for realtime
ALTER TABLE public.messages REPLICA IDENTITY FULL;
ALTER TABLE public.notifications REPLICA IDENTITY FULL;
ALTER TABLE public.consultations REPLICA IDENTITY FULL;
ALTER TABLE public.chats REPLICA IDENTITY FULL;

-- Add tables to realtime publication
ALTER PUBLICATION supabase_realtime ADD TABLE public.messages;
ALTER PUBLICATION supabase_realtime ADD TABLE public.notifications;
ALTER PUBLICATION supabase_realtime ADD TABLE public.consultations;
ALTER PUBLICATION supabase_realtime ADD TABLE public.chats;

-- =====================================================
-- INDEXES
-- =====================================================

CREATE INDEX idx_consultations_patient_id ON public.consultations(patient_id);
CREATE INDEX idx_consultations_doctor_id ON public.consultations(doctor_id);
CREATE INDEX idx_consultations_status ON public.consultations(status);
CREATE INDEX idx_messages_consultation_id ON public.messages(consultation_id);
CREATE INDEX idx_messages_sender_id ON public.messages(sender_id);
CREATE INDEX idx_notifications_user_id ON public.notifications(user_id);
CREATE INDEX idx_notifications_is_read ON public.notifications(is_read);
CREATE INDEX idx_user_roles_user_id ON public.user_roles(user_id);
CREATE INDEX idx_user_roles_role ON public.user_roles(role);
CREATE INDEX idx_doctors_info_profile_id ON public.doctors_info(profile_id);
CREATE INDEX idx_chats_consultation_id ON public.chats(consultation_id);
CREATE INDEX idx_media_assets_consultation_id ON public.media_assets(consultation_id);
CREATE INDEX idx_patient_feedback_user_id ON public.patient_feedback(user_id);
CREATE INDEX idx_doctor_registrations_status ON public.doctor_registrations(status);
CREATE INDEX idx_doctor_registrations_email ON public.doctor_registrations(email);

-- =====================================================
-- SCHEMA COMPLETE
-- =====================================================
