// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nydetrcmdwjkellmqjki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55ZGV0cmNtZHdqa2VsbG1xamtpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTMzOTgsImV4cCI6MjA2NTQ4OTM5OH0.tmsmMfEmqks9pk9HL0jPrf0wiOCkfsTLbocMCxtXGZE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);